



%% Import data from text file.
% Script for importing data from the following text file:
%
%    H:\matlab\2_temp_matlab.csv
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2016/05/10 11:14:25

%% Initialize variables.

clear;

for yr = ['3','4']

    
    
    
    
filename = ['H:\data\2_temp_matlab' yr '.csv'];
delimiter = ',';
startRow = 2;


%% Format string for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
%	column6: double (%f)
%   column7: double (%f)
%	column8: double (%f)
%   column9: double (%f)
%	column10: double (%f)
%   column11: double (%f)
%	column12: double (%f)
%   column13: double (%f)
%	column14: double (%f)
%   column15: text (%s)
%	column16: double (%f)
%   column17: double (%f)
%	column18: double (%f)
%   column19: double (%f)
%	column20: double (%f)
%   column21: double (%f)
%	column22: double (%f)
%   column23: double (%f)
%	column24: double (%f)
%   column25: double (%f)
%	column26: double (%f)
%   column27: double (%f)
%	column28: double (%f)
%   column29: double (%f)
%	column30: double (%f)
%   column31: double (%f)
%	column32: double (%f)
%   column33: double (%f)
%	column34: double (%f)
%   column35: double (%f)
%	column36: double (%f)
%   column37: double (%f)
%	column38: double (%f)
%   column39: double (%f)
%	column40: double (%f)
%   column41: double (%f)
%	column42: text (%s)
%   column43: double (%f)
%	column44: double (%f)
%   column45: double (%f)
%	column46: double (%f)
%   column47: double (%f)
%	column48: double (%f)
%   column49: double (%f)
%	column50: double (%f)
%   column51: double (%f)
%	column52: double (%f)
%   column53: double (%f)
%	column54: double (%f)
%   column55: double (%f)
%	column56: double (%f)
%   column57: double (%f)
%	column58: double (%f)
%   column59: double (%f)
%	column60: double (%f)
%   column61: double (%f)
%	column62: double (%f)
%   column63: double (%f)
%	column64: double (%f)
%   column65: double (%f)
%	column66: double (%f)
%   column67: double (%f)
%	column68: double (%f)
%   column69: double (%f)
%	column70: double (%f)
%   column71: double (%f)
%	column72: double (%f)
%   column73: double (%f)
%	column74: double (%f)
%   column75: double (%f)
%	column76: double (%f)
%   column77: double (%f)
%	column78: double (%f)
%   column79: double (%f)
%	column80: double (%f)
%   column81: double (%f)
%	column82: double (%f)
%   column83: double (%f)
%	column84: double (%f)
%   column85: double (%f)
%	column86: double (%f)
%   column87: double (%f)
%	column88: double (%f)
%   column89: double (%f)
%	column90: double (%f)
%   column91: double (%f)
%	column92: double (%f)
%   column93: double (%f)
%	column94: double (%f)
%   column95: double (%f)
%	column96: double (%f)
%   column97: double (%f)
%	column98: double (%f)
%   column99: double (%f)
%	column100: double (%f)
%   column101: double (%f)
%	column102: double (%f)
%   column103: double (%f)
%	column104: double (%f)
%   column105: double (%f)
%	column106: double (%f)
%   column107: double (%f)
%	column108: double (%f)
%   column109: double (%f)
%	column110: double (%f)
%   column111: double (%f)
%	column112: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%f%f%f%f%f%f%f%f%f%f%f%f%s%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%s%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines' ,startRow-1, 'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
persnr = dataArray{:, 1};
alter = dataArray{:, 2};
ded_rente0_exp = dataArray{:, 3};
ded_rente0_expA = dataArray{:, 4};
ded_rente1_exp = dataArray{:, 5};
ded_rente1_expA = dataArray{:, 6};
ded_rente2_exp = dataArray{:, 7};
ded_rente2_expA = dataArray{:, 8};
ded_rente3_exp = dataArray{:, 9};
ded_rente3_expA = dataArray{:, 10};
ded_rente4_exp = dataArray{:, 11};
ded_rente4_expA = dataArray{:, 12};
ded_rente5_exp = dataArray{:, 13};
ded_rente5_expA = dataArray{:, 14};
zeit = dataArray{:, 15};
gebjahr = dataArray{:, 16};
retire = dataArray{:, 17};
deu = dataArray{:, 18};
ausbil = dataArray{:, 19};
lohn_p85 = dataArray{:, 20};
jahre_e = dataArray{:, 21};
jahre_e55 = dataArray{:, 22};
jahre_e60 = dataArray{:, 23};
jahre_bzeit40 = dataArray{:, 24};
jahre_alo55 = dataArray{:, 25};
jahre_alo5560 = dataArray{:, 26};
jahre_schule = dataArray{:, 27};
tentgelt = dataArray{:, 28};
zustand = dataArray{:, 29};
besch = dataArray{:, 30};
alozs = dataArray{:, 31};
tz = dataArray{:, 32};
stib = dataArray{:, 33};
tenure2 = dataArray{:, 34};
tenure5 = dataArray{:, 35};
bsmon = dataArray{:, 36};
tz_ever = dataArray{:, 37};
rrz_akt = dataArray{:, 38};
del_alo = dataArray{:, 39};
del_atz = dataArray{:, 40};
atztentgelt = dataArray{:, 41};
del_alo_cens = dataArray{:, 42};
year_month = dataArray{:, 43};
year1 = dataArray{:, 44};
tentgelt_pred = dataArray{:, 45};
lohn_exp = dataArray{:, 46};
zfage720 = dataArray{:, 47};
zfage726 = dataArray{:, 48};
zfage732 = dataArray{:, 49};
zfage738 = dataArray{:, 50};
zfage744 = dataArray{:, 51};
zfage750 = dataArray{:, 52};
zfage756 = dataArray{:, 53};
zfage762 = dataArray{:, 54};
zfage768 = dataArray{:, 55};
zfage774 = dataArray{:, 56};
zfage780 = dataArray{:, 57};
zf0 = dataArray{:, 58};
zfalo0 = dataArray{:, 59};
rente0 = dataArray{:, 60};
rente0A = dataArray{:, 61};
zf1 = dataArray{:, 62};
zfalo1 = dataArray{:, 63};
rente1 = dataArray{:, 64};
rente1A = dataArray{:, 65};
zf2 = dataArray{:, 66};
zfalo2 = dataArray{:, 67};
rente2 = dataArray{:, 68};
rente2A = dataArray{:, 69};
zf3 = dataArray{:, 70};
zfalo3 = dataArray{:, 71};
rente3 = dataArray{:, 72};
rente3A = dataArray{:, 73};
zf4 = dataArray{:, 74};
zfalo4 = dataArray{:, 75};
rente4 = dataArray{:, 76};
rente4A = dataArray{:, 77};
zf5 = dataArray{:, 78};
zfalo5 = dataArray{:, 79};
rente5 = dataArray{:, 80};
rente5A = dataArray{:, 81};
rente0_exp = dataArray{:, 82};
rente0_expA = dataArray{:, 83};
rente1_exp = dataArray{:, 84};
rente1_expA = dataArray{:, 85};
rente2_exp = dataArray{:, 86};
rente2_expA = dataArray{:, 87};
rente3_exp = dataArray{:, 88};
rente3_expA = dataArray{:, 89};
rente4_exp = dataArray{:, 90};
rente4_expA = dataArray{:, 91};
rente5_exp = dataArray{:, 92};
rente5_expA = dataArray{:, 93};
alosatz = dataArray{:, 94};
bula = dataArray{:, 95};
alo_kr = dataArray{:, 96};
mon_delete = dataArray{:, 97};
altersg = dataArray{:, 98};
lohn_p85log = dataArray{:, 99};
krank00 = dataArray{:, 100};
krank05 = dataArray{:, 101};
tenure1 = dataArray{:, 102};
tenure2p = dataArray{:, 103};
tenure3 = dataArray{:, 104};
tenure4 = dataArray{:, 105};
jahre_e2 = dataArray{:, 106};
jahre_ue = dataArray{:, 107};
jahre_ue2 = dataArray{:, 108};
w_fin = dataArray{:, 109};
w_house = dataArray{:, 110};
prob_house = dataArray{:, 111};
own_house = dataArray{:, 112};

%% Clear temporary variables
clearvars filename delimiter startRow formatSpec fileID dataArray ans;

savefile= ['H:\data\ws' yr 'b.mat'];
save(savefile);

end;